# Generated by Django 5.1.7 on 2025-03-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_follow_unique_together_follow_unique_follow_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="follow",
            name="prevent_self_follow",
        ),
    ]
